logging.level.root: INFO
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
spring.http.log-request-details: true

location:
  hosts:
  -
    id: "PFC"
    address: "https://api.run.pivotal.io"
    conntimeout: 3000
    version: "2.132.0"
    resource: "/v2/info"
  -
    id: "BLUEMIX"
    address: "https://api.ng.bluemix.net"
    conntimeout: 3000
    version: "2.106.0"
    resource: "/v2/info"
